[build]
  command = "npm run build"
  publish = "dist"

[build.environment]
  NODE_VERSION = "20"
  NPM_VERSION = "10"

# Optional: if you ever put source code in a subfolder, set base here:
# base = "web"
